<?xml version="1.0"?>

<!--
    
The purpose of this file is to represent the actions to be taken when the VideoMonkey GUI is manipulated. The GUI contains a list of files to be encoded. For each input file, information about it (size, bitrate, frame rate, etc.) is stored. When any change is made to the GUI (selecting a menu item, sliding a slider, checking a box, etc.) 

File Syntax
===========

The Command file contains an outer <videomonkey> element with one of each children:

 <default_device> - parameters used by any device when not overridden, with children:
     <quality> - set of stops for quality slider, with children:
         <quality_stop> - one quality stop, with attributes:
             title - the title of the tick mark
     <performance> - values for performance menu, with children:
         <performance_item> - one item in menu, with attributes and children:
             title - title of this item in menu
             <param>, <command>, <script> - see below
     <param>, <command>, <script> - see below
         
 <devices> - List of devices in device menu, with children:
     <device_group> - A grouping of devices. Each groups has a title and groups are separated by a line, 
                      with attributes and children:
         title - title for this group
         <common_device> - features common to all devices in this group, with same children as <default_device>
         <device> - device in this group, with same children as <default_device> and additional attributes and children:
             title - title for this device
             icon - name of the icon image to use for this device
             enabled - whether or not this device is enabled in the device list (true | false)
             <checkbox> - this describes a checkbox, with attributes and children:
                 which - which checkbox (0-n)
                 title - title on the checkbox
                 enabled - whether or not this checkbox is enabled (true | false)
                 <checked_item> - parameters used when this checkbox is checked, with children:
                     <param>, <command>, <script> - see below
                 <unchecked_item> - parameters used when this checkbox is not checked, with children:
                     <param>, <command>, <script> - see below
             <menu> - this describes a menu, with children:
                 which - which menu (0-n)
                 title - title on the menu
                 enabled - whether or not this menu is enabled (true | false)
                 <menu_item> - one entry in the menu, with attributes and children:
                     title - title of this menu item
                     <param>, <command>, <script> - see below
                 <unchecked_item> - parameters used when this checkbox is not checked, with children:
                     <param>, <command>, <script> - see below
            <param>, <command>, <script> - see below

<script> element
================

Wherever a script element is allowed, there can be 0 or more. If more than one, all scripts are concatenated and executed as one. Scripts have access to the normal JavaScript objects (Object, String, Array, etc.). In addition, there is a log() function which takes 0 or more parameters, each of which is converted to a string and output to the console. After all strings of a log() function are printed, a newline is printed. Log entries are prefixed for identification.

<param> element
===============

Wherever a param element is allowed, there can be 0 or more. Each element adds a property to the 'params' property whose property name is obtained from the 'id' attribute and whose property value is obtained from the 'value' attribute.

<command> element
=================

Wherever a command element is allowed, there can be 0 or more. Commands are just like params except that the property value is the contents of the element, rather than the 'value' attribute. All newline characters are stripped from the content string, as are any leading of trailing whitespace characters.

Execution
=========

The workhorse elements are the <param>, <command>, <script>. These contain the instructions which ultimately lead to a recipe to use for the encoding job. In general params and commands are added to the JavaScript 'params' object in one pass. And then the scripts are executed in a separate pass. So even later defined params and commands are accessible to earlier scripts. Scripts are executed according to the elements which contain them in the following order:

    1) selected <performance_item> from <default_device>
    2) <default_device>
    3) selected <performance_item> from <common_device> for selected <device>
    4) <common_device> for selected <device>
    5) selected <performance_item> from selected <device>
    6) <checked_item> or <unchecked_item> entry from each <checkbox> in selected <device>
    7) selected <menu_item> entry from each <menu> in selected <device>
    8) selected <device>
    
The result of this script execution is a string in 'params.recipe' which is the recipe to be executed. See below for recipe syntax. These scripts are executed when any UI control is changed. This includes the slider, which executes the scripts for each move. The script is executed in turn for each file selected for encoding. This pass of script execution is to fill in the file list entries. When encoding is started, the scripts are executed again for the currently encoding file and the recipe is used to start the encoding. Once encoding is finished, the scripts are executed for the next file, and so on.

Javascript Params
=================

Each time scripts execute, a number of parameters are preloaded into the 'params' property. These are:

Param Name              Value
==========              =====

ffmpeg                  ffmpeg command path
qt_export               qt_export command path (used to extract audio from some file types)
movtoy4m                movtoy4m command path (used to extract video from some file types)
yuvadjust               yuvadjust command path (used to adjust video saturation, hue, etc.)
yuvcorrect              yuvcorrect command path (used to perform color correction on raw yuv data)

input_file              Current input file path
output_file             Current output file path
tmp_audio_file          Path to a temp file to which audio can be saved
pass_log_file           Path to the ffmpeg pass log file, used for 2 pass encoding
input_video_width       Width, in pixels, of the input file
input_video_height      Height, in pixels, of the input file
input_frame_rate        Frame rate, in fps, of the input file
input_video_bitrate     Bitrate of the video in the input file
input_video_aspect      Video aspect ratio (may be different from width/height for non-square pixels)
input_video_codec       Name of the video codec of the input file

is_quicktime            "true" if the input file is quicktime
has_audio               "true" if the input file contains an audio track

quality                 The current setting of the quality slider (0-1 between tick marks)
quality_stop            Which tick mark is currently to the left of the slider (0 to #ticks-1)
title                   Title of the currently selected device

limit_output_params     "true" if output params should be limited to be no larger than input

num_cpus                Number of CPUs to use during encoding

After executing all the scripts (see Execution) the system expects the following properties to be set in the 'params' property:

Param Name              Value
==========              =====

recipe                  Recipe to use for the current encoding
output_video_width      Width, in pixels, of the output file
output_video_height     Height, in pixels, of the output file
audio_quality           A string indicating the audio quality of the output file (usually "low", "medium" or "high")
output_video_bitrate    Approximate bitrate of the output video

output_format_name      Displayed format of the container
output_video_codec_name Displayed video codec
output_video_profile_name Displayed profile of the video
output_video_level_name Displayed level of this video
output_video_frame_rate Framerate of the output file (actual frame rate in fps * 1000)

output_audio_codec_name Displayed audio codec
output_audio_bitrate    Audio bitrate
output_audio_sample_rate Sample rate of audio
output_audio_channels   Number of channels of audio

The recipe is used for the actual encoding, the others are used to update the file entries.

Recipes 
=======

A recipe is essentially a shell script to be passed to /bin/sh. A param (from the global 'params' object) can be included with a '$' followed by the property name. For instance if there were a 'params.foo' property with the value "very nice", then the recipe "This is a $foo command" would translate to "This is a very nice command". To include a literal '$' simply use two consecutively ('$$'). 

A property name is anything from the character after the '$' to the next whitespace character. Or you can use parantheses around the property name to concatenate with non-whitespace characters. For instance "This is the $(foo)st command" would translate to "This is the very nicest command".

-->

<!-- 
<!DOCTYPE videomonkey [
    <!ELEMENT videomonkey    (default_device|devices)*>
    <!ELEMENT script    (#PCDATA)>
    <!ELEMENT param    EMPTY>
        <!ATTLIST param id CDATA "">
        <!ATTLIST param value CDATA "">
    <!ELEMENT default_device    (quality|performance|script|param|command)*>
    <!ELEMENT common_device     (quality|performance|script|param|command)*>
    <!ELEMENT devices    (device_group*)>
    <!ELEMENT command    (#PCDATA)>
        <!ATTLIST command id CDATA "">
    <!ELEMENT quality    (quality_stop*)>
    <!ELEMENT quality_stop  EMPTY>
        <!ATTLIST quality_stop title CDATA "">
    <!ELEMENT performance    (performance_item*)>
    <!ELEMENT performance_item    (script|param|command)*>
        <!ATTLIST performance_item title CDATA "">
    <!ELEMENT device_group    (common_device?,device*)>
        <!ATTLIST device_group title CDATA "">
    <!ELEMENT device    (quality|performance|script|param|command|checkbox|menu)*>
        <!ATTLIST device title CDATA "">
        <!ATTLIST device icon CDATA "">
        <!ATTLIST device enabled CDATA "">
    <!ELEMENT checkbox    (checked_item|unchecked_item)*>
        <!ATTLIST checkbox which CDATA "">
        <!ATTLIST checkbox title CDATA "">
        <!ATTLIST checkbox enabled CDATA "">
     <!ELEMENT checked_item    (script|param|command)*>
    <!ELEMENT unchecked_item    (script|param|command)*>
    <!ELEMENT menu    (menu_item*)>
        <!ATTLIST menu which CDATA "">
        <!ATTLIST menu title CDATA "">
        <!ATTLIST menu enabled CDATA "">
     <!ELEMENT menu_item    (script|param|command)*>
        <!ATTLIST menu_item title CDATA "">
]>
-->

<videomonkey>
    <default_device>
        <command id="ffmpeg_single_pass_options">
            -vpre $ffmpeg_vpre $ffmpeg_profile
        </command>
        <command id="ffmpeg_pass1_options">
            -vpre $ffmpeg_vpre_pass1 -pass 1 -passlogfile "$pass_log_file" $ffmpeg_profile
        </command>
        <command id="ffmpeg_pass2_options">
            -vpre $ffmpeg_vpre -pass 2 -passlogfile "$pass_log_file" $ffmpeg_profile
        </command>
        <command id="ffmpeg_normal"> $ffmpeg -threads $num_cpus -y -i "$input_file" </command>
		<!-- Added by ebj -->
		<command id="ffmpeg_thumbnail"> $ffmpeg -y -i "$output_file" </command>
		<!-- End addition -->
        <command id="yuv_to_ffmpeg_av"> $ffmpeg -threads $num_cpus -y -i - -i "$tmp_audio_file" </command>
        <command id="yuv_to_ffmpeg_v"> $ffmpeg -threads $num_cpus -y -i - </command>
        <command id="quicktime_av_single_pass">
            $quicktime_to_yuv | $yuv_to_ffmpeg_av $ffmpeg_options $ffmpeg_single_pass_options "$output_file"
        </command>
        <command id="quicktime_av_pass1"> 
            $quicktime_to_yuv | $yuv_to_ffmpeg_av $ffmpeg_options $ffmpeg_pass1_options "$output_file" 
        </command>
        <command id="quicktime_av_pass2">
            $quicktime_to_yuv | $yuv_to_ffmpeg_av $ffmpeg_options $ffmpeg_pass2_options "$output_file"
        </command>
        <command id="quicktime_v_single_pass"> 
            $quicktime_to_yuv | $yuv_to_ffmpeg_v $ffmpeg_options $ffmpeg_single_pass_options "$output_file"
        </command>
        <command id="quicktime_v_pass1">
            $quicktime_to_yuv | $yuv_to_ffmpeg_v $ffmpeg_options $ffmpeg_pass1_options "$output_file"
        </command>
        <command id="quicktime_v_pass2">
            $quicktime_to_yuv | $yuv_to_ffmpeg_v $ffmpeg_options $ffmpeg_pass2_options "$output_file"
        </command>
        <command id="normal_pass1">
            $ffmpeg_normal $ffmpeg_options $ffmpeg_pass1_options "$output_file"
        </command>
        <command id="normal_pass2">
            $ffmpeg_normal $ffmpeg_options $ffmpeg_pass2_options "$output_file"
        </command>
        <command id="normal_single_pass">
            $ffmpeg_normal $ffmpeg_options $ffmpeg_single_pass_options "$output_file"
        </command>
        <script>
            <![CDATA[
            
             function caseInsensitiveCompare(a,b) { return a.toLowerCase() == b.toLowerCase() }
            
            function audio(type)
            {
                switch(type) {
                    case "low":
                        params.output_audio_bitrate =  16000;
                        params.output_audio_sample_rate = 11025;
                        params.output_audio_channels = 1;
                        params.audio_quality = "Low";
                        break;
                    case "medium":
                        params.output_audio_bitrate =  32000;
                        params.output_audio_sample_rate = 22050;
                        params.output_audio_channels = 1;
                        params.audio_quality = "Medium";
                        break;
                    case "high":
                        params.output_audio_bitrate = 128000;
                        params.output_audio_sample_rate = 48000;
                        params.output_audio_channels = 2;
                        params.audio_quality = "High";
                        break;
                    case "avi":
                        params.output_audio_bitrate = 128000;
                        params.output_audio_sample_rate = 48000;
                        params.output_audio_channels = 2;
                        params.audio_quality = "High";
                        break;
                    case "mp4Low":
                        params.output_audio_bitrate =  12000;
                        params.output_audio_sample_rate = 11025;
                        params.output_audio_channels = 1;
                        params.audio_quality = "Low";
                        break;
                    case "wmv":
                        params.output_audio_bitrate =  128000;
                        params.output_audio_sample_rate = 44100;
                        params.output_audio_channels = 2;
                        params.audio_quality = "High";
                        break;
                    case "wmvlow":
                        params.output_audio_bitrate =  24000;
                        params.output_audio_sample_rate = 11025;
                        params.output_audio_channels = 1;
                        params.audio_quality = "Low";
                        break;
                }
            }
            
            function mpegaudio(type)
            {
                
                switch(type) {
                    case "low":
                        params.output_audio_bitrate =  32000;
                        params.output_audio_sample_rate = 22050;
                        params.output_audio_channels = 1;
                        params.audio_quality = "Low";
                        break;
                    case "high":
                        params.output_audio_bitrate =  128000;
                        params.output_audio_sample_rate = 48000;
                        params.output_audio_channels = 2;
                        params.audio_quality = "High";
                        break;
                    case "vcd":
                        params.output_audio_bitrate = 224000;
                        params.output_audio_sample_rate = 44100;
                        params.output_audio_channels = 2;
                        params.audio_quality = "High";
                        break;
                    case "svcd":
                        params.output_audio_bitrate = 224000;
                        params.output_audio_sample_rate = 48000;
                        params.output_audio_channels = 2;
                        params.audio_quality = "High";
                        break;
                    case "hd":
                        params.output_audio_bitrate = 192000;
                        params.output_audio_sample_rate = 48000;
                        params.output_audio_channels = 2;
                        params.audio_quality = "High";
                        break;
                }
            }
            
            function bool(v)
            {
                if (typeof(v) == "number")
                    return v != 0;
                if (typeof(v) == "boolean")
                    return v;
                if (typeof(v) == "string")
                    return v != "false" && v != "";
                return false;
            }
            
            function number(v)
            {
                if (typeof(v) == "number")
                    return v;
                if (typeof(v) == "boolean")
                    return v ? 1 : 0;
                if (typeof(v) == "string")
                    return parseFloat(v);
                return 0;
            }
            
            function standardizeVideoCodecName(name)
            {
                if (caseInsensitiveCompare(name, "vc-1"))
                    return "wmv3";
                if (caseInsensitiveCompare(name, "avc") || caseInsensitiveCompare(name, "avc1"))
                    return "h.264";
                return name;
            }
            
            function adjustVideoParams()
            {
                params.special_qt = params.is_quicktime == "true" && params.input_video_codec == "wmv3";
            
                // set the frame rate
                params.frame_rate = 1;
                if (params.title != "Apple TV" && number(params.quality_stop) == 0)
                    params.frame_rate = 0.5;

                params.output_video_frame_rate = params.input_frame_rate * params.frame_rate;
                
                // All devices have a max frame rate of 30fps
                if (params.output_video_frame_rate > 30)
                    params.output_video_frame_rate = 30;
                
                // Set output frame size
                var inputWidth = params.input_video_width;
                var inputHeight = params.input_video_height;
                var inputAspect = inputWidth / inputHeight;
                if (Math.abs(inputAspect - params.input_video_aspect) > 0.01) {
                    if (inputAspect < params.input_video_aspect) {
                        // stretch horizontally
                        inputWidth = inputHeight * params.input_video_aspect;
                    }
                    else {
                        // stretch vertically
                        inputHeight = inputWidth / params.input_video_aspect;
                    }
                }
                
                // adjust for limit_output_params
                if (bool(params.limit_output_params)) {
                    if (params.frame_width > inputWidth || params.frame_height > inputHeight) {
                        params.frame_width = inputWidth;
                        params.frame_height = inputHeight;
                    }
                    
                    if (params.output_video_bitrate > params.input_video_bitrate)
                        params.output_video_bitrate = params.input_video_bitrate;
                }
                
                // Adjust frame rate and frame size based on format_limits for Apple TV
                if (params.title == "Apple TV") {
                    if (params.format_limits == "24fps") {
                        if (params.frame_width > 960 || params.frame_height > 540) {
                            if (params.output_video_frame_rate > 24)
                                params.output_video_frame_rate = 24;
                            if (params.frame_width > 1280)
                                params.frame_width = 1280;
                            if (params.frame_height > 1024)
                                params.frame_height = 1024;
                        }
                    }
                    else {
                        if (params.output_video_frame_rate > 30)
                            params.output_video_frame_rate = 30;
                        if (params.frame_width > 960)
                            params.frame_width = 960;
                        if (params.frame_height > 540)
                            params.frame_height = 540;
                    }
                }
                
                if(params.title == "MPEG" && params.profile != "none" || params.title == "PSP") {
                
                }else{
                    // adjust video frame size
                    inputAspect = inputWidth / inputHeight;

                    var requestedAspect = params.frame_width / params.frame_height;
                    
                    if (inputAspect > requestedAspect) {
                        // shorten height
                        params.output_video_width = params.frame_width;
                        params.output_video_height = params.frame_width / inputAspect;
                    }
                    else {
                        // shorten width
                        params.output_video_height = params.frame_height;
                        params.output_video_width = params.frame_height * inputAspect;
                    }
                    
                    // Make frame size divisible by 16
                    params.output_video_width = Math.round(params.output_video_width / 16) * 16;
                    params.output_video_height = Math.round(params.output_video_height / 16) * 16;
                }
                
                // One more problem. If we are frame size limited (Apple TV) then 
                // rounding could have pushed us over that limit.
                // We need to make sure the width and height
                // are below the maximums.
                if (params.title == "Apple TV") {
                    if (params.format_limits == "24fps") {
                        if (params.output_video_width > 1280)
                            params.output_video_width -= 16;
                        if (params.output_video_height > 1024)
                            params.output_video_height -= 16;
                    }
                    else {
                        if (params.output_video_width > 960)
                            params.output_video_width -= 16;
                        if (params.output_video_height > 540)
                            params.output_video_height -= 16;
                    }
                }

                //params.ffmpeg_vcodec = bool(params.h264) ? "libx264" : "mpeg4";
                params.output_video_codec_name = bool(params.h264) ? "H.264" : "MPEG-4"
                params.output_audio_codec_name = "AAC";
                
                
                // adjust vpre for baseline if needed
                // FIXME: For some reason, creating anything other than baseline does not work
                // on Apple TV. This seems to have something to do with VFR of the input source?
                // For now always use baseline
                //if (title != "Apple TV")
                params.ffmpeg_profile = "-bf 0 -coder 0 -flags2 -wpred-dct8x8";
            }
            
            audio("high");
            
            adjustVideoParams();
           
            ]]>
        </script>
        <quality>
            <quality_stop title="Peor" />
            <quality_stop title="Baja" />
            <quality_stop title="Normal" />
            <quality_stop title="Alta" />
            <quality_stop title="Mejor" />
        </quality>
        <performance>
            <performance_item title="La más rápida">
                <param id="is_2_pass" value="false" />
                <param id="ffmpeg_vpre" value="fastest" />
                <param id="ffmpeg_profile" value="-bf 1" />
            </performance_item>
            <performance_item title="Rápida">
                <param id="is_2_pass" value="false" />
                <param id="ffmpeg_vpre" value="default" />
                <param id="ffmpeg_profile" value="-bf 1" />
            </performance_item>
            <performance_item title="Normal">
                <param id="is_2_pass" value="false" />
                <param id="ffmpeg_vpre" value="normal" />
                <param id="ffmpeg_profile" value="-bf 4" />
            </performance_item>
            <performance_item title="Normal (2 pasadas)">
                <param id="is_2_pass" value="true" />
                <param id="ffmpeg_vpre" value="normal" />
                <param id="ffmpeg_vpre_pass1" value="normal-pass1" />
                <param id="ffmpeg_profile" value="-bf 4" />
             </performance_item>
            <performance_item title="Alta calidad">
                <param id="is_2_pass" value="false" />
                <param id="ffmpeg_vpre" value="hq" />
                <param id="ffmpeg_profile" value="-bf 16" />
            </performance_item>
            <performance_item title="Alta calidad (2 pasadas)">
                <param id="is_2_pass" value="true" />
                <param id="ffmpeg_vpre" value="hq" />
                <param id="ffmpeg_vpre_pass1" value="hq-pass1" />
                <param id="ffmpeg_profile" value="-bf 16" />
           </performance_item>
        </performance>
        <param id="ffmpeg_vcodec" value="libx264" />
        <param id="ffmpeg_acodec" value="libfaac" />
        <param id="video_suffix" value="mp4" />
    </default_device>
    
    <devices>
    
        <!--
        
            iTunes Group
            
        -->
        <device_group title="iTunes">
            <common_device>
                <command id="ffmpeg_options">
                    -vcodec $ffmpeg_vcodec -b $output_video_bitrate -s $(output_video_width)x$(output_video_height) 
                        -aspect $(output_video_width):$(output_video_height) -r $(output_video_frame_rate)
                    -async 50 -acodec $ffmpeg_acodec -ab $output_audio_bitrate -ar $output_audio_sample_rate 
                        -ac $output_audio_channels
                </command>
                <command id="quicktime_to_audio_file">
                    $qt_export "$input_file" --video=0 "$tmp_audio_file"
                </command>
                <command id="correct_yuv">
                    $yuvcorrect -v 0 -Y LUMINANCE_1.20_0_255_0_255 -Y CHROMINANCE_0_1.04_128_1.04_128_0_255
                </command>
                <command id="quicktime_to_yuv">
                    $movtoy4m -f -w $input_video_width -h $input_video_height -F $(output_video_frame_rate) 
                        -a $(output_video_width):$(output_video_height) "$input_file" | $correct_yuv 
                </command>
                <script>
                    <![CDATA[
    
                    // At this point, we know what 2 quality stops we are between (params.quality_stop 
                    // and params.quality_stop+1) and we know what percentage of the way between the 
                    // two we are (params.quality). We also which device we have selected 
                    // (params.title), whether we are doing h.264 or mpeg4 (params.h264), and whether 
                    // we want to optimize for TV or iPod (params.for_tv). From this we need to 
                    // compute params.frame_width, params.frame_height, params.audio_quality and
                    // params.output_video_bitrate.
                    
                    // We support a number of standard frame sizes. After adjusting these sizes according to the flags
                    // (h264, forTV), we determine the actual frame size using these as maximum values, taking
                    // into account aspect ratio.
                    
                    params.output_format_name = "MPEG-4";
                    
                    var frameSizes = {
                        "tiny":  [  192,  144 ],
                        "small": [  320,  240 ],
                        "iphone":[  480,  320 ],
                        "sdef":  [  640,  480 ],
						"ipad":  [ 1280,  720 ],
                        "idef":  [ 1280,  720 ],
                        "hdef":  [ 1920, 1080 ]
                    };
                    
                    var deviceFrameSizeMap = {
                        //                              0           1           2           3           4
                        "Dispositivos Apple":
                        [
                            [   "small",    "iphone",   "sdef",     "sdef",     "sdef" ],   // mp4 && for iPod
                            [   "small",    "iphone",   "sdef",     "sdef",     "sdef" ],   // mp4 && for TV
                            [   "small",    "iphone",   "sdef",     "sdef",     "sdef" ],   // h.264 && for iPod
                            [   "small",    "iphone",   "sdef",     "sdef",     "sdef" ]    // h.264 && for TV